window:
	g++ -o window.exe window.cpp -I ../SFML-2.6.1/include/ -L ../SFML-2.6.1/lib -lsfml-window -lsfml-system -lsfml-graphics -O3 -Wall -Wextra 

misc:
	g++ -o misc.exe misc.cpp -I ../SFML-2.6.1/include/ -L ../SFML-2.6.1/lib lsfml-window -lsfml-system -lsfml-graphics -O3 -Wall -Wextra 

collision:
	g++ -o collision.exe collision.cpp -I ../SFML-2.6.1/include/  -L ../SFML-2.6.1/lib  -lsfml-window -lsfml-system -lsfml-graphics -O3 -Wall -Wextra 

floats:
	g++ -o floats.exe floats.cpp -I ../SFML-2.6.1/include/  -L ../SFML-2.6.1/lib -lsfml-window -lsfml-system -lsfml-graphics -O3 -Wall -Wextra 

#unused
Linux:
	g++ -o window.out window.cpp -I /usr/include/ -lsfml-window  -L ../SFML-2.6.1/lib -lsfml-system -lsfml-graphics -O3 -Wall -Wextra 

